language: csharp
sudo: false
mono:
  - latest
env: TEST_VERSION=1.0.1
solution: Travis.Nuget.Example.sln
script:
  - /bin/sh ./build.sh
  - /bin/sh ./test.sh
deploy:
  skip_cleanup: true
  provider: script
  script:
    - /bin/sh ./deploy.sh
  on:
    tags: true
